version: 3
services:
	dev:
		build:
			context: .
			dockerfile: Dockerfile.dev
		ports:
			- '8080:8080'
		volumes:
			- /app/node_modules
			- ./app
	prod:
		build:
			context: .
			dockerfile: Dockerfile
		ports:
			- '80:80'
